include:
  - local: '.gitlab-ci/variables.yml'
  - local: '.gitlab-ci/build.yml'
  - local: '.gitlab-ci/deploy.yml'

stages:
  - build
  - deploy

# Global default settings
default:
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure