variables:
  # App Specifications
  MIN_CPU: 250m
  MIN_MEMORY: 512Mi
  MAX_CPU: 1000m
  MAX_MEMORY: 1Gi
  PORT: 80
  PROXY_BODY_SIZE: 5m

  # Image and Deployment Variables, It's better to not change these variables below
  # because they are used in the deploy script
  VERSION: $CI_COMMIT_TAG
  TAG_IMAGE_NAME: "$registry_host/$CI_PROJECT_PATH:$VERSION"
  APP_NAME: "$CI_PROJECT_NAME"
  INGRESS_HOST: "$CI_PROJECT_PATH_SLUG"

  # App Variables, you can add your own variables here
  # App variables must have the prefix "PODS_"
  NEXT_PUBLIC_API_URL: $backend_url